### ISSUE TITLE
Help with HA config

### ISSUE THREAD

**Issue by kababoom** [rrooggiieerr/esphome-livingcolors1#1]
First of all thanks for creating this, found out about it via FB, really like to control my Philips Living Colours device via HA...

I got the cc2500 connected as mentioned in the readme (yep need steady hands) and installed the sample in esphome but experience some issues with the sample config....

channel_number is not recognised (throws and error)
where did you get the 'address' from?

Current logging:

[22:36:01][C][logger:443]: Logger:
[22:36:01][C][logger:444]:   Level: DEBUG
[22:36:01][C][logger:445]:   Log Baud Rate: 115200
[22:36:01][C][logger:447]:   Hardware UART: UART0
[22:36:01][C][spi:067]: SPI bus:
[22:36:01][C][spi:068]:   CLK Pin: GPIO14
[22:36:01][C][spi:069]:   SDI Pin: GPIO12
[22:36:01][C][spi:070]:   SDO Pin: GPIO13
[22:36:01][C][spi:072]:   Using HW SPI: SPI
[22:36:01][C][light:103]: Light 'LivingColors'
[22:36:01][C][light:105]:   Default Transition Length: 0.0s
[22:36:01][C][light:106]:   Gamma Correct: 0.00
[22:36:01][C][cc2500:136]: CC2500 component:
[22:36:01][C][cc2500:137]:   CS PIN: GPIO15
[22:36:01][C][cc2500:139]:   Output power: 255
[22:36:01][C][livingcolors1:012]: Living Colors 1st generation component:
[22:36:01][C][livingcolors1.light:014]: Living Colors gen 1 light:
[22:36:01][C][livingcolors1.light:015]:   0x0000000000000004
[22:36:01][C][mdns:115]: mDNS:
[22:36:01][C][mdns:116]:   Hostname: livingcolors1
[22:36:01][C][ota:097]: Over-The-Air Updates:
[22:36:01][C][ota:098]:   Address: livingcolors1.local:8266
[22:36:01][C][api:139]: API Server:
[22:36:01][C][api:140]:   Address: livingcolors1.local:6053
[22:36:01][C][api:142]:   Using noise encryption: YES

-M

**Comment by rrooggiieerr** [comment]
Thanks! I have an update ahead which shows the mentioned address in the logging but that needs some finalisation. I'll only have time for that next week earliest.

For the time being you might want to give this code a try, https://github.com/philipplive/Philips-Living-Colors-Gen1-with-NodeMCU which also logs the address to the console

**Comment by kababoom** [comment]
Alright, was able to get the code running and get the address:

20:25:54.872 -> Vorhandene Adressen im Speicher:
20:25:54.901 -> 195 137 119 55 121 194 55 91 

setLamps does not work due to getColors(), skipped quickly with:
```
    plc.setLamps(CMD_ON, 255, 255, 255);
```

Anyway got the address and the automatic lamp turn on which is already really cool 😄 

Looking forward diving deeper but also got limited available time.

**Comment by kababoom** [comment]
Converted the address to hex and did load it up in esp-home, no more errors... 

Now need to figure out what sensors to add I guess??

**Comment by rrooggiieerr** [comment]
Thanks for your updates! Yes, the address needs to be hex. Not sure what sensor you're talking about, the light should be available as an RGB light and controllable accordingly.

**Comment by kababoom** [comment]
Hmm I don't see any new devices or entities.

**Comment by rrooggiieerr** [comment]
You have added your ESPHome to HA I suppose? This is what I got in HA after adding the ESP:

<img width="337" alt="Screenshot 2024-01-13 at 14 13 22" src="https://github.com/rrooggiieerr/esphome-livingcolors1/assets/18603534/d594f6d8-9dbe-47bb-992f-9ab8da84d991">
<img width="596" alt="Screenshot 2024-01-13 at 14 13 38" src="https://github.com/rrooggiieerr/esphome-livingcolors1/assets/18603534/f069e56f-9f30-48f5-87c7-4692f6b86b37">
<img width="606" alt="Screenshot 2024-01-13 at 14 13 51" src="https://github.com/rrooggiieerr/esphome-livingcolors1/assets/18603534/44b07b1b-8e1d-4358-b022-ffd0eb0caf18">

**Comment by kababoom** [comment]
Of course, but don't see any new entities..

<img width="719" alt="image" src="https://github.com/rrooggiieerr/esphome-livingcolors1/assets/16404944/adc2a35f-f2f6-4292-9cf1-ecdee718f7f5">

**Comment by rrooggiieerr** [comment]
You should also add the ESPHome device to the ESPHome integration under Settings > Devices & Services, But normally HA should recognise a new ESPHome device.

Maybe you have reused an ESP and removed or disabled the previous device is was part of? The ESPHome integration uses the MAC address as a unique key, and this gives problems when you reuse an ESP for an other project. Then you can go to Settings > Devices & Services, click Add Integration and search for ESPHome and give the hostname or IP address of your ESP to have it readded

**Comment by kababoom** [comment]
ESPHome is installed and working, several other ESP8266 and ESP32 boards are there and have working entities.
I might have used this board previously so good advice on the manual add, will look into that.

**Comment by rrooggiieerr** [comment]
Wonderfull! Enjoy controlling your LivingColors from HA.

Just being curious, which CC2500 module are you using and what is the reach? The one I'm using as pictured in the Readme only has a reach of about 2 meters. I've also got a blue CC2500 module with an actual SMD chip instead of a black blob but that one isn't doing much better.

**Comment by rrooggiieerr** [comment]
That one looks similar to the one I'm using. My experience is that you can also power the light from 5 Volts so that would make it easy to connect the light and the ESP from the same (USB) power source.

I actually would like the code to also support receiving commands from the remote, that goes a bit further than discovering the remote ID. However I would like to use interrupts to make this work instead of polling. I haven't succeeded in making the CC2500 module trigger the interrupt. In the same time, I don't use the remote anymore since I have the light integrated in HA, so the urgency for me is not high and only like it to be in the code for sake of completeness.

If I got time I'll clean up my (not yet working) interrupt code and publish it on GitHub.

**Comment by PvdGulik** [comment]
> Alright, was able to get the code from philipplive running and get the address:
> 
> 20:25:54.872 -> Vorhandene Adressen im Speicher: 20:25:54.901 -> 195 137 119 55 121 194 55 91
> 
> setLamps does not work due to getColors(), skipped quickly with:
> 
> ```
>     plc.setLamps(CMD_ON, 255, 255, 255);
> ```
> 
> Anyway got the address and the lamp now automagically turns on which is already really cool 😄
> 
> Looking forward diving deeper but also got limited available time.
> 
> Note: Of course this is the hard way, just soldering an Action Tuya RBG led controller into the lamp would be much easier but this is much more fun ...

> Alright, was able to get the code from philipplive running and get the address:

How did you manage to compile that code (ino-file) to a NodeMCU (ESP8266) with Arduino IDE?

I got an error while compiling:

```
/Users/******/Downloads/Philips-Living-Colors-Gen1-with-NodeMCU-master/philipslivingcolor/PhilipsLampLib.cpp: In member function 'bool PhilipsLampLib::addLamp(uint8_t*)':
/Users/******/Downloads/Philips-Living-Colors-Gen1-with-NodeMCU-master/philipslivingcolor/PhilipsLampLib.cpp:244:10: error: control reaches end of non-void function [-Werror=return-type]
  244 |     debug("Adressspeicer voll!");
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors

exit status 1

Compilation error: control reaches end of non-void function [-Werror=return-type]
```

Thanks for your help!
